use_frameworks!

platform :ios, '11.0'

target 'LotsOfExtensions_Tests' do
  pod 'LotsOfExtensions', :path => '../'
	pod 'Then'
  
end

target 'Example' do
  pod 'LotsOfExtensions', :path => '../'
  pod 'Then'
  pod 'TinyConstraints'
  
end
