# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

branches:
  only:
  - develop
  - master

osx_image: xcode12.2
language: swift
xcode_workspace: Example/LotsOfExtensions.xcworkspace
xcode_scheme: LotsOfExtensions-Tests
podfile: Example/Podfile

jobs:
  include:
  - xcode_destination: platform=iOS Simulator,OS=11.0.1,name=iPhone X
  - xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X
  - xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
  - xcode_destination: platform=iOS Simulator,OS=14.0.1,name=iPhone 11

# cache: cocoapods
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example